<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="NextReleaseProblemSolution" nsURI="NextReleaseProblemSolution"
    nsPrefix="NextReleaseProblemSolution">
  <eClassifiers xsi:type="ecore:EClass" name="NRPSolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" eType="#//RequirementSelection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementSelection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="ecore:EClass NextReleaseProblem#//Requirement"/>
  </eClassifiers>
</ecore:EPackage>
