<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="orchestrationSolution" nsURI="http://crepe.examples/service-composition-solution"
    nsPrefix="composition-solution">
  <eClassifiers xsi:type="ecore:EClass" name="Solution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concretePlans" upperBound="-1"
        eType="ecore:EClass http://OrchestrationMM/1.0#//ConcretePlan" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
